#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [[ -n "$1" ]]; then
  LOCAL_GO="$1"
  shift
else
  LOCAL_GO=../Gumnut-go
fi

echo "==> Linking with local directory"
go mod tidy -e
go mod edit -replace github.com/gumnut-ai/photos-sdk-go="$LOCAL_GO"
